# Generated by AppyScript — https://github.com/rahulbachina/appyscript
# Target: ESP32 / M5Stack Core S3 SE (MicroPython)
# Do not edit — re-generate from your .appy source file

from applaa_robot import Robot, wait_ms
import uasyncio as asyncio
import random

robot = Robot()

async def _handler_start():
    ringing = 0
    seconds = 10
    robot.voice.say("Alarm set for 10 seconds. Sweet dreams!")
    await asyncio.sleep_ms(500)
    robot.display.expression("sleep")
    while seconds > 0:
        await asyncio.sleep_ms(1000)
        seconds = (seconds - 1)
        await asyncio.sleep_ms(10)
    ringing = 1
    robot.display.expression("alert")
    while ringing > 0:
        robot.voice.say("WAKE UP!")
        await asyncio.sleep_ms(500)
        robot.voice.play("success")
        await asyncio.sleep_ms(1000)
        await asyncio.sleep_ms(10)
    robot.display.expression("calm")
    robot.voice.say("Good morning!")
    await asyncio.sleep_ms(500)

async def _handler_button_a():
    while True:
        if robot.button_a():
            ringing = 0
            robot.display.expression("happy")
        await asyncio.sleep_ms(50)

async def main():
    tasks = []
    tasks.append(asyncio.create_task(_handler_start()))
    tasks.append(asyncio.create_task(_handler_button_a()))
    await asyncio.gather(*tasks)

asyncio.run(main())