# Generated by AppyScript — https://github.com/rahulbachina/appyscript
# Target: Adafruit Circuit Playground Bluefruit (CircuitPython)
# Do not edit — re-generate from your .appy source file

import time
import board
import digitalio
from adafruit_circuitplayground import cp

# AppyScript robot interface for Circuit Playground

def spin_dance():
    # turn right 180°
    time.sleep(0.2)
    # turn left 180°
    time.sleep(0.2)

def wave():
    # move left at 50%
    # Connect motors to A1/A2 with a motor driver
    # move right at 50%
    # Connect motors to A1/A2 with a motor driver
    # stop motors

while True:
    if cp.shake(shake_threshold=20):
        cp.pixels.fill((255, 165, 0))   # excited
        print("Let's dance!")
        cp.play_tone(440, 0.2)
        for _i in range(3):
            spin_dance()
        wave()
        cp.pixels.fill((0, 255, 0))   # happy
    if cp.button_a:
        cp.pixels.fill((0, 128, 128))   # calm
        # stop motors
    time.sleep(0.05)