# Generated by AppyScript — https://github.com/rahulbachina/appyscript
# Target: ESP32 / M5Stack Core S3 SE (MicroPython)
# Do not edit — re-generate from your .appy source file

from applaa_robot import Robot, wait_ms
import uasyncio as asyncio
import random

robot = Robot()

def spin_dance():
    robot.move.turn_right(degrees=180)
    await asyncio.sleep_ms(200)
    robot.move.turn_left(degrees=180)
    await asyncio.sleep_ms(200)

def wave():
    robot.move.left(speed=50)
    await asyncio.sleep_ms(300)
    robot.move.stop()
    robot.move.right(speed=50)
    await asyncio.sleep_ms(300)
    robot.move.stop()
    robot.move.stop()

async def _handler_shaken():
    while True:
        if robot.sensor.shaken():
            robot.display.expression("excited")
            robot.voice.say("Let's dance!")
            await asyncio.sleep_ms(500)
            for _i in range(3):
                spin_dance()
            wave()
            robot.display.expression("happy")
        await asyncio.sleep_ms(50)

async def _handler_button_a():
    while True:
        if robot.button_a():
            robot.display.expression("calm")
            robot.move.stop()
        await asyncio.sleep_ms(50)

async def main():
    tasks = []
    tasks.append(asyncio.create_task(_handler_shaken()))
    tasks.append(asyncio.create_task(_handler_button_a()))
    await asyncio.gather(*tasks)

asyncio.run(main())