# Generated by AppyScript — https://github.com/rahulbachina/appyscript
# Target: ESP32 / M5Stack Core S3 SE (MicroPython)
# Do not edit — re-generate from your .appy source file

from applaa_robot import Robot, wait_ms
import uasyncio as asyncio
import random

robot = Robot()

async def _handler_start():
    robot.voice.say("Shake me to roll the dice!")
    await asyncio.sleep_ms(500)
    robot.display.expression("happy")

async def _handler_shaken():
    while True:
        if robot.sensor.shaken():
            robot.display.expression("dizzy")
            await asyncio.sleep_ms(500)
            roll = random.randint(1, 6)
            robot.voice.say(str("You rolled ") + str(str(roll)))
            await asyncio.sleep_ms(500)
            if roll > 4:
                robot.display.expression("excited")
                robot.voice.play("success")
            else:
                robot.display.expression("calm")
        await asyncio.sleep_ms(50)

async def main():
    tasks = []
    tasks.append(asyncio.create_task(_handler_start()))
    tasks.append(asyncio.create_task(_handler_shaken()))
    await asyncio.gather(*tasks)

asyncio.run(main())