# Generated by AppyScript — https://github.com/rahulbachina/appyscript
# Target: ESP32 / M5Stack Core S3 SE (MicroPython)
# Do not edit — re-generate from your .appy source file

from applaa_robot import Robot, wait_ms
import uasyncio as asyncio
import random

robot = Robot()

async def _handler_start():
    robot.voice.say("Hold your hand in front of me and move it slowly!")
    await asyncio.sleep_ms(500)
    robot.display.expression("happy")
    while True:
        if robot.sensor.distance() < 15:
            robot.move.backward(speed=40)
            await asyncio.sleep_ms(1000)
            robot.move.stop()
            robot.display.expression("confused")
        else:
            if robot.sensor.distance() < 25:
                robot.move.stop()
                robot.display.expression("happy")
            else:
                robot.move.forward(speed=40)
                await asyncio.sleep_ms(1000)
                robot.move.stop()
                robot.display.expression("thinking")
        await asyncio.sleep_ms(10)

async def _handler_button_a():
    while True:
        if robot.button_a():
            robot.move.stop()
            robot.voice.say("Okay, taking a break!")
            await asyncio.sleep_ms(500)
            robot.display.expression("calm")
        await asyncio.sleep_ms(50)

async def main():
    tasks = []
    tasks.append(asyncio.create_task(_handler_start()))
    tasks.append(asyncio.create_task(_handler_button_a()))
    await asyncio.gather(*tasks)

asyncio.run(main())