# Generated by AppyScript — https://github.com/rahulbachina/appyscript
# Target: ESP32 / M5Stack Core S3 SE (MicroPython)
# Do not edit — re-generate from your .appy source file

from applaa_robot import Robot, wait_ms
import uasyncio as asyncio
import random

robot = Robot()

async def _handler_start():
    fortunes = []
    fortunes.append("Yes!")
    fortunes.append("No way.")
    fortunes.append("Ask again later.")
    fortunes.append("Definitely!")
    fortunes.append("Hmm... maybe.")
    robot.voice.say("Think of a question, then shake me!")
    await asyncio.sleep_ms(500)
    robot.display.expression("thinking")

async def _handler_shaken():
    while True:
        if robot.sensor.shaken():
            robot.display.expression("dizzy")
            await asyncio.sleep_ms(1000)
            n = random.randint(1, 5)
            answer = fortunes[n - 1]
            robot.voice.say(str(answer))
            await asyncio.sleep_ms(500)
            robot.display.expression("happy")
        await asyncio.sleep_ms(50)

async def main():
    tasks = []
    tasks.append(asyncio.create_task(_handler_start()))
    tasks.append(asyncio.create_task(_handler_shaken()))
    await asyncio.gather(*tasks)

asyncio.run(main())