# Generated by AppyScript — https://github.com/rahulbachina/appyscript
# Target: ESP32 / M5Stack Core S3 SE (MicroPython)
# Do not edit — re-generate from your .appy source file

from applaa_robot import Robot, wait_ms
import uasyncio as asyncio
import random

robot = Robot()

async def _handler_sensor_distance():
    while True:
        if robot.sensor.distance() < 30:
            robot.voice.say("INTRUDER ALERT!")
            await asyncio.sleep_ms(500)
            robot.display.expression("angry")
            robot.move.turn_right(degrees=180)
            await asyncio.sleep_ms(1000)
            robot.display.expression("alert")
        await asyncio.sleep_ms(50)

async def _forever_loop():
    while True:
        if robot.sensor.distance() > 60:
            robot.display.expression("happy")
        await asyncio.sleep_ms(500)
        await asyncio.sleep_ms(10)

async def main():
    tasks = []
    tasks.append(asyncio.create_task(_handler_sensor_distance()))
    tasks.append(asyncio.create_task(_forever_loop()))
    await asyncio.gather(*tasks)

asyncio.run(main())