// Generated by AppyScript — https://github.com/rahulbachina/appyscript
// Target: Arduino Uno / Nano / Mega (Arduino C++)
// Do not edit — re-generate from your .appy source file

#include <AppyRobot.h>

AppyRobot robot;

// User variables — declared at global scope for loop() access
// (AppyScript will generate these from your "let" statements)

void setup() {
    Serial.begin(115200);
    robot.begin();
}

void loop() {
    if (robot.distance() < 30) {
        Serial.println("INTRUDER ALERT!"); robot.beep(440, 200);
        robot.showExpression("angry");
        robot.turn("right", 180);
        delay(1000);
        robot.showExpression("alert");
    }
    if (robot.distance() > 60) {
        robot.showExpression("happy");
    }
    delay(500);
    delay(50);
}
