# Generated by AppyScript — https://github.com/rahulbachina/appyscript
# Target: Raspberry Pi Pico W (MicroPython)
# Do not edit — re-generate from your .appy source file

# Pico W — applaa_robot_pico library required
from applaa_robot_pico import Robot, wait_ms
import uasyncio as asyncio
from machine import Pin, PWM, ADC

robot = Robot()

async def _handler_sensor_distance():
    while True:
        if robot.sensor.distance() < 30:
            print("INTRUDER ALERT!")   # say
            print("expression: angry")
            robot.turn(direction="right", degrees=180)
            await asyncio.sleep_ms(1000)
            print("expression: alert")
        await asyncio.sleep_ms(50)

async def _forever_loop():
    while True:
        if robot.sensor.distance() > 60:
            print("expression: happy")
        await asyncio.sleep_ms(500)
        await asyncio.sleep_ms(10)

async def main():
    tasks = []
    tasks.append(asyncio.create_task(_handler_sensor_distance()))
    tasks.append(asyncio.create_task(_forever_loop()))
    await asyncio.gather(*tasks)

asyncio.run(main())