# Generated by AppyScript — https://github.com/rahulbachina/appyscript
# Target: ESP32 / M5Stack Core S3 SE (MicroPython)
# Do not edit — re-generate from your .appy source file

from applaa_robot import Robot, wait_ms
import uasyncio as asyncio
import random

robot = Robot()

async def _handler_start():
    robot.display.expression("happy")
    robot.voice.say("Hello! I am Appy!")
    await asyncio.sleep_ms(500)
    await asyncio.sleep_ms(1000)
    robot.display.expression("calm")

async def main():
    tasks = []
    tasks.append(asyncio.create_task(_handler_start()))
    await asyncio.gather(*tasks)

asyncio.run(main())