# Generated by AppyScript — https://github.com/rahulbachina/appyscript
# Target: ESP32 / M5Stack Core S3 SE (MicroPython)
# Do not edit — re-generate from your .appy source file

from applaa_robot import Robot, wait_ms
import uasyncio as asyncio
import random

robot = Robot()

def wiggle():
    robot.move.turn_left(degrees=45)
    robot.move.turn_right(degrees=90)
    robot.move.turn_left(degrees=45)

def strut():
    robot.move.forward(speed=60)
    await asyncio.sleep_ms(1000)
    robot.move.stop()
    robot.move.backward(speed=60)
    await asyncio.sleep_ms(1000)
    robot.move.stop()

async def _handler_button_a():
    while True:
        if robot.button_a():
            robot.voice.say("Let's dance!")
            await asyncio.sleep_ms(500)
            robot.display.expression("excited")
            for _i in range(4):
                wiggle()
                strut()
            robot.move.turn_right(degrees=360)
            robot.voice.play("success")
            robot.display.expression("happy")
        await asyncio.sleep_ms(50)

async def _handler_button_b():
    while True:
        if robot.button_b():
            robot.move.stop()
            robot.voice.say("Dance break!")
            await asyncio.sleep_ms(500)
            robot.display.expression("calm")
        await asyncio.sleep_ms(50)

async def main():
    tasks = []
    tasks.append(asyncio.create_task(_handler_button_a()))
    tasks.append(asyncio.create_task(_handler_button_b()))
    await asyncio.gather(*tasks)

asyncio.run(main())