# Generated by AppyScript — https://github.com/rahulbachina/appyscript
# Target: ESP32 / M5Stack Core S3 SE (MicroPython)
# Do not edit — re-generate from your .appy source file

from applaa_robot import Robot, wait_ms
import uasyncio as asyncio
import random

robot = Robot()

async def _handler_start():
    robot.voice.say("Night light ready! I watch the room for you.")
    await asyncio.sleep_ms(500)
    robot.display.expression("calm")

async def _handler_sensor_light():
    while True:
        if robot.sensor.light() < 20:
            robot.display.expression("happy")
            robot.display.show("LIGHT ON")
            robot.voice.play("success")
            robot.voice.say("It's dark, turning on my glow!")
            await asyncio.sleep_ms(500)
        await asyncio.sleep_ms(50)

async def _handler_sensor_light():
    while True:
        if robot.sensor.light() > 60:
            robot.display.expression("sleep")
            robot.display.show("LIGHT OFF")
            robot.voice.say("Nice and bright, light off.")
            await asyncio.sleep_ms(500)
        await asyncio.sleep_ms(50)

async def main():
    tasks = []
    tasks.append(asyncio.create_task(_handler_start()))
    tasks.append(asyncio.create_task(_handler_sensor_light()))
    tasks.append(asyncio.create_task(_handler_sensor_light()))
    await asyncio.gather(*tasks)

asyncio.run(main())