# Generated by AppyScript — https://github.com/rahulbachina/appyscript
# Target: ESP32 / M5Stack Core S3 SE (MicroPython)
# Do not edit — re-generate from your .appy source file

from applaa_robot import Robot, wait_ms
import uasyncio as asyncio
import random

robot = Robot()

async def _handler_start():
    happiness = 5
    robot.display.expression("happy")
    robot.voice.say("I'm your pet robot! Press my buttons to play with me!")
    await asyncio.sleep_ms(500)

async def _handler_button_a():
    while True:
        if robot.button_a():
            happiness = (happiness + 2)
            robot.display.expression("excited")
            robot.voice.play("success")
            robot.voice.say("Yay! I love you!")
            await asyncio.sleep_ms(500)
        await asyncio.sleep_ms(50)

async def _handler_button_b():
    while True:
        if robot.button_b():
            happiness = (happiness + 1)
            robot.display.expression("happy")
            robot.voice.say("Thanks for the pat!")
            await asyncio.sleep_ms(500)
        await asyncio.sleep_ms(50)

async def _handler_timer_10000ms():
    while True:
        happiness = (happiness - 1)
        if happiness < 3:
            robot.display.expression("sad")
            robot.voice.say("I feel ignored... play with me!")
            await asyncio.sleep_ms(500)
        await asyncio.sleep_ms(10000)

async def main():
    tasks = []
    tasks.append(asyncio.create_task(_handler_start()))
    tasks.append(asyncio.create_task(_handler_button_a()))
    tasks.append(asyncio.create_task(_handler_button_b()))
    tasks.append(asyncio.create_task(_handler_timer_10000ms()))
    await asyncio.gather(*tasks)

asyncio.run(main())