# Generated by AppyScript — https://github.com/rahulbachina/appyscript
# Target: ESP32 / M5Stack Core S3 SE (MicroPython)
# Do not edit — re-generate from your .appy source file

from applaa_robot import Robot, wait_ms
import uasyncio as asyncio
import random

robot = Robot()

async def _handler_start():
    score = robot.brain.load("score", 0)
    robot.voice.say(str("Welcome back! Your score is ") + str(str(score)))
    await asyncio.sleep_ms(500)
    robot.display.expression("happy")

async def _handler_button_a():
    while True:
        if robot.button_a():
            answer = input("What is 5 + 3?")
            if answer == "8":
                score = (score + 1)
                robot.brain.save("score", score)
                robot.voice.say(str("Correct! Score: ") + str(str(score)))
                await asyncio.sleep_ms(500)
                robot.display.expression("excited")
                robot.voice.play("success")
            else:
                robot.voice.say("Not quite! The answer is 8")
                await asyncio.sleep_ms(500)
                robot.display.expression("sad")
        await asyncio.sleep_ms(50)

async def _handler_button_b():
    while True:
        if robot.button_b():
            if score < 3:
                robot.voice.say("Keep practising — you can do it!")
                await asyncio.sleep_ms(500)
                robot.display.expression("thinking")
            else:
                if (score >= 3) and (score <= 7):
                    robot.voice.say(str(str("Good work — score is ") + str(str(score))) + str("!"))
                    await asyncio.sleep_ms(500)
                    robot.display.expression("happy")
                else:
                    if score > 7:
                        robot.voice.say(str(str("Amazing! Score: ") + str(str(score))) + str(" — you're a star!"))
                        await asyncio.sleep_ms(500)
                        robot.display.expression("excited")
        await asyncio.sleep_ms(50)

async def main():
    tasks = []
    tasks.append(asyncio.create_task(_handler_start()))
    tasks.append(asyncio.create_task(_handler_button_a()))
    tasks.append(asyncio.create_task(_handler_button_b()))
    await asyncio.gather(*tasks)

asyncio.run(main())