# Generated by AppyScript — https://github.com/rahulbachina/appyscript
# Target: ESP32 / M5Stack Core S3 SE (MicroPython)
# Do not edit — re-generate from your .appy source file

from applaa_robot import Robot, wait_ms
import uasyncio as asyncio
import random

robot = Robot()

async def _handler_start():
    robot.voice.say("Watch the screen. Press A the moment you see GO!")
    await asyncio.sleep_ms(500)
    robot.display.expression("thinking")
    delay = random.randint(2, 6)
    while delay > 0:
        await asyncio.sleep_ms(1000)
        delay = (delay - 1)
        await asyncio.sleep_ms(10)
    robot.display.show("GO!")
    robot.display.expression("excited")

async def _handler_button_a():
    while True:
        if robot.button_a():
            robot.voice.play("success")
            robot.display.expression("happy")
            robot.voice.say("Fast fingers! You win!")
            await asyncio.sleep_ms(500)
        await asyncio.sleep_ms(50)

async def _handler_button_b():
    while True:
        if robot.button_b():
            robot.display.expression("confused")
            robot.voice.say("Wrong button! Press A!")
            await asyncio.sleep_ms(500)
        await asyncio.sleep_ms(50)

async def main():
    tasks = []
    tasks.append(asyncio.create_task(_handler_start()))
    tasks.append(asyncio.create_task(_handler_button_a()))
    tasks.append(asyncio.create_task(_handler_button_b()))
    await asyncio.gather(*tasks)

asyncio.run(main())