# Generated by AppyScript — https://github.com/rahulbachina/appyscript
# Target: ESP32 / M5Stack Core S3 SE (MicroPython)
# Do not edit — re-generate from your .appy source file

from applaa_robot import Robot, wait_ms
import uasyncio as asyncio
import random

robot = Robot()

async def _handler_start():
    brightness = 50
    brightness = robot.brain.load("brightness", 0)
    robot.voice.say(str(str("Lamp on at ") + str(str(brightness))) + str("%"))
    await asyncio.sleep_ms(500)

async def _handler_button_a():
    while True:
        if robot.button_a():
            brightness = (brightness + 10)
            if brightness > 100:
                brightness = 100
            robot.brain.save("brightness", brightness)
            robot.voice.say(str(str("Brightness: ") + str(str(brightness))) + str("%"))
            await asyncio.sleep_ms(500)
        await asyncio.sleep_ms(50)

async def _handler_button_b():
    while True:
        if robot.button_b():
            brightness = 0
            robot.brain.save("brightness", brightness)
            robot.voice.say("Lamp off")
            await asyncio.sleep_ms(500)
        await asyncio.sleep_ms(50)

async def _handler_timer_60000ms():
    while True:
        if brightness < 20:
            robot.voice.say("Lamp is dim — press A to brighten")
            await asyncio.sleep_ms(500)
        else:
            if (brightness >= 20) and (brightness <= 70):
                robot.voice.say("Lamp is comfortable")
                await asyncio.sleep_ms(500)
            else:
                if brightness > 70:
                    robot.voice.say("Lamp is bright")
                    await asyncio.sleep_ms(500)
        await asyncio.sleep_ms(60000)

async def main():
    tasks = []
    tasks.append(asyncio.create_task(_handler_start()))
    tasks.append(asyncio.create_task(_handler_button_a()))
    tasks.append(asyncio.create_task(_handler_button_b()))
    tasks.append(asyncio.create_task(_handler_timer_60000ms()))
    await asyncio.gather(*tasks)

asyncio.run(main())