# Generated by AppyScript — https://github.com/rahulbachina/appyscript
# Target: ESP32 / M5Stack Core S3 SE (MicroPython)
# Do not edit — re-generate from your .appy source file

from applaa_robot import Robot, wait_ms
import uasyncio as asyncio
import random

robot = Robot()

async def _handler_start():
    steps = 0
    robot.voice.say("Strap me on and start walking!")
    await asyncio.sleep_ms(500)
    robot.display.expression("happy")

async def _handler_shaken():
    while True:
        if robot.sensor.shaken():
            steps = (steps + 1)
            robot.brain.remember("steps", steps)
            robot.voice.say(str("Steps: ") + str(str(steps)))
            await asyncio.sleep_ms(500)
            if steps > 100:
                robot.display.expression("excited")
                robot.voice.play("success")
        await asyncio.sleep_ms(50)

async def _handler_button_a():
    while True:
        if robot.button_a():
            robot.voice.say(str("Total steps today: ") + str(str(steps)))
            await asyncio.sleep_ms(500)
        await asyncio.sleep_ms(50)

async def _handler_button_b():
    while True:
        if robot.button_b():
            steps = 0
            robot.brain.remember("steps", steps)
            robot.voice.say("Counter reset!")
            await asyncio.sleep_ms(500)
            robot.display.expression("calm")
        await asyncio.sleep_ms(50)

async def main():
    tasks = []
    tasks.append(asyncio.create_task(_handler_start()))
    tasks.append(asyncio.create_task(_handler_shaken()))
    tasks.append(asyncio.create_task(_handler_button_a()))
    tasks.append(asyncio.create_task(_handler_button_b()))
    await asyncio.gather(*tasks)

asyncio.run(main())