# Generated by AppyScript — https://github.com/rahulbachina/appyscript
# Target: ESP32 / M5Stack Core S3 SE (MicroPython)
# Do not edit — re-generate from your .appy source file

from applaa_robot import Robot, wait_ms
import uasyncio as asyncio
import random

robot = Robot()

async def _handler_start():
    score = 0
    robot.display.expression("excited")
    robot.voice.say("Let's do the 5 times table!")
    await asyncio.sleep_ms(500)
    await asyncio.sleep_ms(1000)
    for _i in range(5):
        robot.voice.say("What is 5 times?")
        await asyncio.sleep_ms(500)
        robot.display.expression("thinking")
        await asyncio.sleep_ms(3000)
        score = (score + 1)
    robot.voice.say("Great job!")
    await asyncio.sleep_ms(500)
    robot.display.expression("happy")

async def _handler_button_a():
    while True:
        if robot.button_a():
            robot.display.expression("happy")
            robot.voice.say("Correct!")
            await asyncio.sleep_ms(500)
        await asyncio.sleep_ms(50)

async def _handler_button_b():
    while True:
        if robot.button_b():
            robot.display.expression("sad")
            robot.voice.say("Try again!")
            await asyncio.sleep_ms(500)
        await asyncio.sleep_ms(50)

async def main():
    tasks = []
    tasks.append(asyncio.create_task(_handler_start()))
    tasks.append(asyncio.create_task(_handler_button_a()))
    tasks.append(asyncio.create_task(_handler_button_b()))
    await asyncio.gather(*tasks)

asyncio.run(main())