# Generated by AppyScript — https://github.com/rahulbachina/appyscript
# Target: ESP32 / M5Stack Core S3 SE (MicroPython)
# Do not edit — re-generate from your .appy source file

from applaa_robot import Robot, wait_ms
import uasyncio as asyncio
import random

robot = Robot()

async def _handler_start():
    robot.voice.say("Traffic light starting!")
    await asyncio.sleep_ms(500)
    while True:
        robot.display.show("RED")
        robot.display.expression("angry")
        await asyncio.sleep_ms(3000)
        robot.display.show("GREEN")
        robot.display.expression("happy")
        await asyncio.sleep_ms(3000)
        robot.display.show("YELLOW")
        robot.display.expression("alert")
        await asyncio.sleep_ms(1000)
        await asyncio.sleep_ms(10)

async def main():
    tasks = []
    tasks.append(asyncio.create_task(_handler_start()))
    await asyncio.gather(*tasks)

asyncio.run(main())