// AppyScript BaseCodegen
// Abstract base class for all code generators.
// Eliminates the duplication of emitValue / emitCondition / durationMs / emit
// across the ESP32, Arduino, micro:bit, and Pico backends.

import type {
  Program, Value, Condition, Duration, SensorName, FaceExpression,
} from '../ast'
import { SourceMap } from '../sourcemap'
import type { HardwareProfile, GenerateResult } from '../plugins'

export function durationMs(d: Duration): number {
  if (d.unit === 'ms') return d.value
  if (d.unit === 's')  return d.value * 1000
  return d.value * 60000
}

export function durationS(d: Duration): number {
  return durationMs(d) / 1000
}

export abstract class BaseCodegen {
  protected lines: string[] = []
  protected indentLevel = 0
  protected definedFunctions = new Set<string>()
  protected sourceMap = new SourceMap()

  // ── Abstract interface ─────────────────────────────────────────────────────

  /** Map a sensor name to the native call for this platform */
  protected abstract sensorCall(sensor: SensorName): string

  /** Generate the full program */
  abstract generate(program: Program, profile: HardwareProfile): GenerateResult

  // ── Shared code emitters ───────────────────────────────────────────────────

  protected emit(line: string, sourceLine?: number) {
    const generatedLine = this.lines.length + 1
    if (sourceLine !== undefined) {
      this.sourceMap.record(generatedLine, sourceLine)
    }
    this.lines.push('    '.repeat(this.indentLevel) + line)
  }

  protected emitBlank() {
    this.lines.push('')
  }

  protected indent()   { this.indentLevel++ }
  protected dedent()   { this.indentLevel = Math.max(0, this.indentLevel - 1) }

  protected get currentLine() { return this.lines.length + 1 }

  // ── Shared value emitter ───────────────────────────────────────────────────

  protected emitValue(value: Value): string {
    switch (value.kind) {
      case 'number':   return String(value.value)
      case 'string':   return JSON.stringify(value.value)
      case 'bool':     return this.boolLiteral(value.value)
      case 'variable': return value.name
      case 'sensor':   return this.sensorCall(value.sensor)
      case 'binary':
        return `(${this.emitValue(value.left)} ${value.op} ${this.emitValue(value.right)})`
    }
  }

  /** Override in C++ backends */
  protected boolLiteral(v: boolean): string { return v ? 'True' : 'False' }

  // ── Shared condition emitter ───────────────────────────────────────────────

  protected emitCondition(cond: Condition): string {
    switch (cond.kind) {
      case 'sensor':
        return `${this.sensorCall(cond.sensor)} ${cond.op} ${cond.threshold}`
      case 'variable':
        return `${cond.name} ${cond.op} ${this.emitValue(cond.value)}`
      case 'bool':
        return this.boolLiteral(cond.value)
      case 'not':
        return `${this.notKeyword()}(${this.emitCondition(cond.condition)})`
      case 'and':
        return `(${this.emitCondition(cond.left)}) ${this.andKeyword()} (${this.emitCondition(cond.right)})`
      case 'or':
        return `(${this.emitCondition(cond.left)}) ${this.orKeyword()} (${this.emitCondition(cond.right)})`
    }
  }

  protected notKeyword(): string  { return 'not ' }
  protected andKeyword(): string  { return 'and' }
  protected orKeyword(): string   { return 'or' }

  // ── Shared utility ─────────────────────────────────────────────────────────

  protected durationMs(d: Duration): number { return durationMs(d) }
  protected durationS(d: Duration): number  { return durationS(d) }

  protected emitHeader(targetLabel: string, runtime: string) {
    this.emit(`# Generated by AppyScript — https://github.com/rahulbachina/appyscript`)
    this.emit(`# Target: ${targetLabel} (${runtime})`)
    this.emit(`# Do not edit — re-generate from your .appy source file`)
    this.emitBlank()
  }

  protected emitCHeader(targetLabel: string) {
    this.emit(`// Generated by AppyScript — https://github.com/rahulbachina/appyscript`)
    this.emit(`// Target: ${targetLabel} (Arduino C++)`)
    this.emit(`// Do not edit — re-generate from your .appy source file`)
    this.emitBlank()
  }

  protected result(): GenerateResult {
    return {
      code: this.lines.join('\n'),
      sourceMap: this.sourceMap.size > 0 ? this.sourceMap : undefined,
    }
  }
}

// ── Face expression maps ───────────────────────────────────────────────────────

export const ASCII_FACES: Record<FaceExpression, string> = {
  happy:    '(^_^)',
  sad:      '(T_T)',
  thinking: '(o_o)',
  excited:  '\\(^o^)/',
  angry:    '(>_<)',
  alert:    '(!_!)',
  sleep:    '(-_-)zzz',
  calm:     '(~_~)',
  confused: '(?_?)',
  dizzy:    '(@_@)',
}

export const MICROBIT_IMAGES: Record<FaceExpression, string> = {
  happy:    'Image.HAPPY',
  sad:      'Image.SAD',
  thinking: 'Image.SURPRISED',
  excited:  'Image.YES',
  angry:    'Image.ANGRY',
  alert:    'Image.SURPRISED',
  sleep:    'Image.ASLEEP',
  calm:     'Image.CALM',
  confused: 'Image.CONFUSED',
  dizzy:    'Image.ROLL',
}
