// AppyScript → Arduino C++ (Uno / Nano / Mega)
// Output is a complete .ino sketch file.

import type {
  Program, Block, Statement, Trigger, Condition, Value, Duration, FaceExpression,
} from '../ast'

function durationMs(d: Duration): number {
  if (d.unit === 'ms') return d.value
  if (d.unit === 's') return d.value * 1000
  return d.value * 60000
}

export function generateArduino(program: Program): string {
  const gen = new ArduinoGenerator()
  return gen.generate(program)
}

class ArduinoGenerator {
  private setup: string[] = []
  private loop: string[] = []
  private functions: string[] = []
  private globals: string[] = []
  private definedFunctions = new Set<string>()
  private usesSerial = false
  private indent = 0

  generate(program: Program): string {
    const defines = program.blocks.filter(b => b.kind === 'define')
    const whenBlocks = program.blocks.filter(b => b.kind === 'when')
    const foreverBlocks = program.blocks.filter(b => b.kind === 'forever')

    // Globals
    this.globals.push('// Generated by AppyScript — https://github.com/rahulbachina/appyscript')
    this.globals.push('// Target: Arduino (Uno/Nano) with Applaa Robot Shield')
    this.globals.push('#include <AppyRobot.h>')
    this.globals.push('')
    this.globals.push('AppyRobot robot;')
    this.globals.push('')

    // Emit defines as C functions
    for (const block of defines) {
      if (block.kind !== 'define') continue
      this.definedFunctions.add(block.name)
      const lines: string[] = []
      lines.push(`void ${block.name}() {`)
      for (const stmt of block.body) {
        lines.push('  ' + this.emitStatement(stmt))
      }
      lines.push('}')
      lines.push('')
      this.functions.push(...lines)
    }

    // Setup: when start block or init
    const startBlocks = whenBlocks.filter(b => b.kind === 'when' && b.trigger.kind === 'start')
    this.setup.push('void setup() {')
    this.setup.push('  Serial.begin(115200);')
    this.setup.push('  robot.begin();')
    for (const b of startBlocks) {
      if (b.kind === 'when') {
        for (const stmt of b.body) {
          this.setup.push('  ' + this.emitStatement(stmt))
        }
      }
    }
    this.setup.push('}')
    this.setup.push('')

    // Loop
    const nonStartWhen = whenBlocks.filter(b => b.kind === 'when' && b.trigger.kind !== 'start')
    this.loop.push('void loop() {')
    for (const block of nonStartWhen) {
      if (block.kind !== 'when') continue
      const condition = this.triggerToCondition(block.trigger)
      if (condition) {
        this.loop.push(`  if (${condition}) {`)
        for (const stmt of block.body) {
          this.loop.push('    ' + this.emitStatement(stmt))
        }
        this.loop.push('  }')
      }
    }
    for (const block of foreverBlocks) {
      if (block.kind !== 'forever') continue
      for (const stmt of block.body) {
        this.loop.push('  ' + this.emitStatement(stmt))
      }
    }
    this.loop.push('  delay(50);')
    this.loop.push('}')

    return [
      ...this.globals,
      ...this.functions,
      ...this.setup,
      ...this.loop,
    ].join('\n')
  }

  private triggerToCondition(trigger: Trigger): string | null {
    switch (trigger.kind) {
      case 'button_a': return 'robot.buttonA()'
      case 'button_b': return 'robot.buttonB()'
      case 'shaken': return 'robot.shaken()'
      case 'tilted': return 'robot.tilted()'
      case 'received': return 'robot.radioReceived()'
      case 'sensor': {
        const call = this.sensorCall(trigger.sensor)
        return `${call} ${trigger.op} ${trigger.threshold}`
      }
      default: return null
    }
  }

  private sensorCall(sensor: string): string {
    const map: Record<string, string> = {
      distance: 'robot.distance()',
      light: 'robot.light()',
      temperature: 'robot.temperature()',
      touch: 'robot.touch()',
      acceleration: 'robot.accelerationMagnitude()',
    }
    return map[sensor] ?? `robot.sensor_${sensor}()`
  }

  private emitStatement(stmt: Statement): string {
    switch (stmt.kind) {
      case 'move': {
        const speed = stmt.speed ?? 50
        const ms = stmt.duration ? durationMs(stmt.duration) : 0
        if (ms > 0) {
          return `robot.move("${stmt.direction}", ${speed}); delay(${ms}); robot.stop();`
        }
        return `robot.move("${stmt.direction}", ${speed});`
      }
      case 'turn':
        return `robot.turn("${stmt.direction}", ${stmt.degrees});`
      case 'stop':
        return 'robot.stop();'
      case 'say':
        // Arduino: no WiFi TTS by default — print to serial monitor
        return `Serial.println(${JSON.stringify(stmt.text)}); robot.beep(440, 200);`
      case 'play':
        return `robot.playSound(${JSON.stringify(stmt.sound)});`
      case 'show':
        return `robot.showExpression(${JSON.stringify(stmt.expression)});`
      case 'show_text':
        return `robot.showText(${JSON.stringify(stmt.text)});`
      case 'show_number':
        return `robot.showNumber(${this.emitValue(stmt.value)});`
      case 'wait':
        return `delay(${durationMs(stmt.duration)});`
      case 'send':
        return `robot.radioSend(String(${this.emitValue(stmt.message)}));`
      case 'let':
        return `int ${stmt.name} = ${this.emitValue(stmt.value)};`
      case 'set':
        return `${stmt.name} = ${this.emitValue(stmt.value)};`
      case 'remember':
        return `robot.eepromWrite(${JSON.stringify(stmt.name)}, ${stmt.name});`
      case 'do':
        return `${stmt.name}();`
      case 'if': {
        const thenLines = stmt.then.map(s => '  ' + this.emitStatement(s)).join('\n')
        let code = `if (${this.emitCondition(stmt.condition)}) {\n${thenLines}\n}`
        if (stmt.else) {
          const elseLines = stmt.else.map(s => '  ' + this.emitStatement(s)).join('\n')
          code += ` else {\n${elseLines}\n}`
        }
        return code
      }
      case 'repeat': {
        const body = stmt.body.map(s => '  ' + this.emitStatement(s)).join('\n')
        return `for (int _i = 0; _i < ${this.emitValue(stmt.count)}; _i++) {\n${body}\n}`
      }
      case 'while': {
        const body = stmt.body.map(s => '  ' + this.emitStatement(s)).join('\n')
        return `while (${this.emitCondition(stmt.condition)}) {\n${body}\n  delay(10);\n}`
      }
      default:
        return `// TODO: ${(stmt as any).kind}`
    }
  }

  private emitValue(value: Value): string {
    switch (value.kind) {
      case 'number': return String(value.value)
      case 'string': return JSON.stringify(value.value)
      case 'bool': return value.value ? 'true' : 'false'
      case 'variable': return value.name
      case 'sensor': return this.sensorCall(value.sensor)
      case 'binary':
        return `(${this.emitValue(value.left)} ${value.op} ${this.emitValue(value.right)})`
    }
  }

  private emitCondition(cond: Condition): string {
    switch (cond.kind) {
      case 'sensor': return `${this.sensorCall(cond.sensor)} ${cond.op} ${cond.threshold}`
      case 'variable': return `${cond.name} ${cond.op} ${this.emitValue(cond.value)}`
      case 'bool': return cond.value ? 'true' : 'false'
      case 'not': return `!(${this.emitCondition(cond.condition)})`
      case 'and': return `(${this.emitCondition(cond.left)}) && (${this.emitCondition(cond.right)})`
      case 'or': return `(${this.emitCondition(cond.left)}) || (${this.emitCondition(cond.right)})`
    }
  }
}
