// AppyScript → MicroPython (ESP32 / M5Stack Core S3 SE)
// Output is ready to flash with mpremote.

import type {
  Program, Block, Statement, Trigger, Condition, Value, Duration, FaceExpression,
} from '../ast'

const FACE_MAP: Record<FaceExpression, string> = {
  happy:    '(^_^)',
  sad:      '(T_T)',
  thinking: '(o_o)',
  excited:  '\\(^o^)/',
  angry:    '(>_<)',
  alert:    '(!_!)',
  sleep:    '(-_-)zzz',
  calm:     '(~_~)',
  confused: '(?_?)',
  dizzy:    '(@_@)',
}

function durationMs(d: Duration): number {
  if (d.unit === 'ms') return d.value
  if (d.unit === 's') return d.value * 1000
  return d.value * 60000
}

function durationS(d: Duration): number {
  return durationMs(d) / 1000
}

export function generateESP32(program: Program): string {
  const gen = new ESP32Generator()
  return gen.generate(program)
}

class ESP32Generator {
  private lines: string[] = []
  private indent = 0
  private definedFunctions = new Set<string>()

  generate(program: Program): string {
    this.emit('# Generated by AppyScript — https://github.com/rahulbachina/appyscript')
    this.emit('# Target: ESP32 / M5Stack Core S3 SE (MicroPython)')
    this.emit('')
    this.emit('from applaa_robot import Robot, wait_ms')
    this.emit('import uasyncio as asyncio')
    this.emit('')
    this.emit('robot = Robot()')
    this.emit('')

    // Collect define blocks first (user-defined functions)
    const defines = program.blocks.filter(b => b.kind === 'define')
    const others = program.blocks.filter(b => b.kind !== 'define')

    // Emit define blocks as functions
    for (const block of defines) {
      if (block.kind === 'define') {
        this.definedFunctions.add(block.name)
        this.emit(`def ${block.name}():`)
        this.indent++
        this.emitStatements(block.body)
        this.indent--
        this.emit('')
      }
    }

    // Emit event handlers as async tasks
    const whenBlocks = others.filter(b => b.kind === 'when')
    const foreverBlocks = others.filter(b => b.kind === 'forever')

    for (const block of whenBlocks) {
      if (block.kind === 'when') {
        this.emitWhenBlock(block)
      }
    }

    for (const block of foreverBlocks) {
      if (block.kind === 'forever') {
        this.emit('async def _forever_loop():')
        this.indent++
        this.emit('while True:')
        this.indent++
        this.emitStatements(block.body)
        this.emit('await asyncio.sleep_ms(10)')
        this.indent -= 2
        this.emit('')
      }
    }

    // Main entry point
    this.emit('async def main():')
    this.indent++
    this.emit('tasks = []')

    for (const block of whenBlocks) {
      if (block.kind === 'when') {
        this.emit(`tasks.append(asyncio.create_task(_handler_${this.triggerName(block.trigger)}()))`)
      }
    }

    if (foreverBlocks.length > 0) {
      this.emit('tasks.append(asyncio.create_task(_forever_loop()))')
    }

    this.emit('await asyncio.gather(*tasks)')
    this.indent--
    this.emit('')
    this.emit('asyncio.run(main())')

    return this.lines.join('\n')
  }

  private emitWhenBlock(block: { kind: 'when'; trigger: Trigger; body: Statement[] }) {
    const name = this.triggerName(block.trigger)
    this.emit(`async def _handler_${name}():`)
    this.indent++

    // Wrap in appropriate polling or event loop
    const { setup, condition } = this.triggerToCondition(block.trigger)
    if (setup) this.emit(setup)

    if (condition) {
      this.emit('while True:')
      this.indent++
      this.emit(`if ${condition}:`)
      this.indent++
      this.emitStatements(block.body)
      this.indent--
      this.emit('await asyncio.sleep_ms(50)')
      this.indent--
    } else {
      // One-shot trigger (start)
      this.emitStatements(block.body)
    }

    this.indent--
    this.emit('')
  }

  private triggerName(trigger: Trigger): string {
    switch (trigger.kind) {
      case 'button_a': return 'button_a'
      case 'button_b': return 'button_b'
      case 'shaken': return 'shaken'
      case 'tilted': return `tilted${trigger.direction ? '_' + trigger.direction : ''}`
      case 'start': return 'start'
      case 'timer': return `timer_${durationMs(trigger.interval)}ms`
      case 'received': return 'received'
      case 'sensor': return `sensor_${trigger.sensor}`
    }
  }

  private triggerToCondition(trigger: Trigger): { setup?: string; condition?: string } {
    switch (trigger.kind) {
      case 'button_a': return { condition: 'robot.button_a()' }
      case 'button_b': return { condition: 'robot.button_b()' }
      case 'shaken': return { condition: 'robot.sensor.shaken()' }
      case 'tilted': return {
        condition: trigger.direction
          ? `robot.sensor.tilted("${trigger.direction}")`
          : 'robot.sensor.tilted()'
      }
      case 'start': return {} // no condition — runs once
      case 'timer': return {
        setup: `_interval = ${durationMs(trigger.interval)}`,
        condition: 'True'
      }
      case 'received': return { condition: 'robot.radio.received()' }
      case 'sensor': {
        const sensorCall = this.sensorCall(trigger.sensor)
        const threshold = trigger.unit === 'cm' ? trigger.threshold : trigger.threshold
        return { condition: `${sensorCall} ${trigger.op} ${threshold}` }
      }
    }
  }

  private sensorCall(sensor: string): string {
    const map: Record<string, string> = {
      distance: 'robot.sensor.distance()',
      light: 'robot.sensor.light()',
      temperature: 'robot.sensor.temperature()',
      touch: 'robot.sensor.touch()',
      acceleration: 'robot.sensor.acceleration_magnitude()',
    }
    return map[sensor] ?? `robot.sensor.${sensor}()`
  }

  private emitStatements(stmts: Statement[]) {
    if (stmts.length === 0) {
      this.emit('pass')
      return
    }
    for (const stmt of stmts) {
      this.emitStatement(stmt)
    }
  }

  private emitStatement(stmt: Statement) {
    switch (stmt.kind) {
      case 'move': {
        const speed = stmt.speed ?? 50
        const ms = stmt.duration ? durationMs(stmt.duration) : 0
        const dir = stmt.direction === 'backward' ? '-' : ''
        if (ms > 0) {
          this.emit(`robot.move.${stmt.direction}(speed=${speed})`)
          this.emit(`await asyncio.sleep_ms(${ms})`)
          this.emit('robot.move.stop()')
        } else {
          this.emit(`robot.move.${stmt.direction}(speed=${speed})`)
        }
        break
      }
      case 'turn':
        this.emit(`robot.move.turn_${stmt.direction}(degrees=${stmt.degrees})`)
        break
      case 'stop':
        this.emit('robot.move.stop()')
        break
      case 'say':
        this.emit(`robot.voice.say(${JSON.stringify(stmt.text)})`)
        this.emit(`await asyncio.sleep_ms(500)`)
        break
      case 'play':
        this.emit(`robot.voice.play(${JSON.stringify(stmt.sound)})`)
        break
      case 'show':
        this.emit(`robot.display.expression(${JSON.stringify(stmt.expression)})`)
        break
      case 'show_text':
        this.emit(`robot.display.show(${JSON.stringify(stmt.text)})`)
        break
      case 'show_number':
        this.emit(`robot.display.number(${this.emitValue(stmt.value)})`)
        break
      case 'wait':
        this.emit(`await asyncio.sleep_ms(${durationMs(stmt.duration)})`)
        break
      case 'send':
        this.emit(`robot.radio.send(${this.emitValue(stmt.message)})`)
        break
      case 'let':
        this.emit(`${stmt.name} = ${this.emitValue(stmt.value)}`)
        break
      case 'set':
        this.emit(`${stmt.name} = ${this.emitValue(stmt.value)}`)
        break
      case 'remember':
        this.emit(`robot.brain.remember(${JSON.stringify(stmt.name)}, ${stmt.name})`)
        break
      case 'do':
        if (this.definedFunctions.has(stmt.name)) {
          this.emit(`${stmt.name}()`)
        } else {
          this.emit(`# Warning: '${stmt.name}' is not defined`)
        }
        break
      case 'if':
        this.emit(`if ${this.emitCondition(stmt.condition)}:`)
        this.indent++
        this.emitStatements(stmt.then)
        this.indent--
        if (stmt.else) {
          this.emit('else:')
          this.indent++
          this.emitStatements(stmt.else)
          this.indent--
        }
        break
      case 'repeat': {
        const count = this.emitValue(stmt.count)
        this.emit(`for _i in range(${count}):`)
        this.indent++
        this.emitStatements(stmt.body)
        this.indent--
        break
      }
      case 'while':
        this.emit(`while ${this.emitCondition(stmt.condition)}:`)
        this.indent++
        this.emitStatements(stmt.body)
        this.emit('await asyncio.sleep_ms(10)')
        this.indent--
        break
    }
  }

  private emitValue(value: Value): string {
    switch (value.kind) {
      case 'number': return String(value.value)
      case 'string': return JSON.stringify(value.value)
      case 'bool': return value.value ? 'True' : 'False'
      case 'variable': return value.name
      case 'sensor': return this.sensorCall(value.sensor)
      case 'binary':
        return `(${this.emitValue(value.left)} ${value.op} ${this.emitValue(value.right)})`
    }
  }

  private emitCondition(cond: Condition): string {
    switch (cond.kind) {
      case 'sensor': return `${this.sensorCall(cond.sensor)} ${cond.op} ${cond.threshold}`
      case 'variable': return `${cond.name} ${cond.op} ${this.emitValue(cond.value)}`
      case 'bool': return cond.value ? 'True' : 'False'
      case 'not': return `not (${this.emitCondition(cond.condition)})`
      case 'and': return `(${this.emitCondition(cond.left)}) and (${this.emitCondition(cond.right)})`
      case 'or': return `(${this.emitCondition(cond.left)}) or (${this.emitCondition(cond.right)})`
    }
  }

  private emit(line: string) {
    this.lines.push('    '.repeat(this.indent) + line)
  }
}
