// AppyScript → ESPHome YAML
// ESPHome is a system to control ESP8266/ESP32 via YAML config — no MicroPython needed.
// Perfect for smart home devices: sensors, lights, switches, buttons.

import type { Program, Block, Statement, Trigger } from '../ast'
import type { HardwareProfile, GenerateResult } from '../plugins'

export const esphomeBackend = {
  targetId: 'esphome',
  name: 'ESPHome YAML Backend',
  version: '1.0.0',
  generate(program: Program, profile: HardwareProfile): GenerateResult {

    const lines: string[] = [
      '# Generated by AppyScript — https://github.com/rahulbachina/appyscript',
      '# Flash via ESPHome Dashboard or: esphome run this_file.yaml',
      '',
      '# ── Device configuration ──────────────────────────────',
      'esphome:',
      '  name: appyscript-device',
      '  friendly_name: AppyScript Device',
      '',
      'esp32:',
      '  board: esp32dev',
      '  framework:',
      '    type: arduino',
      '',
      '# ── Connectivity ──────────────────────────────────────',
      'wifi:',
      '  ssid: !secret wifi_ssid',
      '  password: !secret wifi_password',
      '  ap:',
      '    ssid: "AppyScript Fallback"',
      '',
      'api:',
      '  encryption:',
      '    key: !secret api_key',
      '',
      'ota:',
      '  - platform: esphome',
      '    password: !secret ota_password',
      '',
      'logger:',
      '',
      '# ── Sensors ───────────────────────────────────────────',
    ]

    // Detect which sensors are used
    const useDistance  = usesFeature(program, 'distance')
    const useLight     = usesFeature(program, 'light')
    const useTemp      = usesFeature(program, 'temperature')
    const useMotion    = usesTrigger(program, 'motion')
    const useDoor      = usesTrigger(program, 'door')

    if(useDistance) {
      lines.push('sensor:')
      lines.push('  - platform: ultrasonic')
      lines.push('    id: distance_sensor')
      lines.push('    name: "Distance"')
      lines.push('    unit_of_measurement: cm')
      lines.push('    trigger_pin: GPIO5')
      lines.push('    echo_pin: GPIO18')
      lines.push('    update_interval: 500ms')
      lines.push('')
    }

    if(useLight) {
      lines.push('  - platform: adc')
      lines.push('    id: light_sensor')
      lines.push('    name: "Light Level"')
      lines.push('    pin: GPIO36')
      lines.push('    update_interval: 1s')
      lines.push('')
    }

    if(useTemp) {
      lines.push('  - platform: dallas_temp')
      lines.push('    id: temp_sensor')
      lines.push('    name: "Temperature"')
      lines.push('    update_interval: 30s')
      lines.push('')
    }

    if(useMotion) {
      lines.push('binary_sensor:')
      lines.push('  - platform: gpio')
      lines.push('    id: motion_sensor')
      lines.push('    name: "Motion"')
      lines.push('    pin:')
      lines.push('      number: GPIO15')
      lines.push('      mode: INPUT_PULLDOWN')
      lines.push('')
    }

    if(useDoor) {
      lines.push('  - platform: gpio')
      lines.push('    id: door_sensor')
      lines.push('    name: "Door"')
      lines.push('    pin:')
      lines.push('      number: GPIO16')
      lines.push('      mode: INPUT_PULLUP')
      lines.push('      inverted: true')
      lines.push('')
    }

    // Buttons
    lines.push('  - platform: gpio')
    lines.push('    id: button_a')
    lines.push('    name: "Button A"')
    lines.push('    pin:')
    lines.push('      number: GPIO0')
    lines.push('      inverted: true')
    lines.push('      mode: INPUT_PULLUP')
    lines.push('')

    // Outputs
    lines.push('# ── Outputs ───────────────────────────────────────────')
    lines.push('output:')
    lines.push('  - platform: ledc')
    lines.push('    id: buzzer_output')
    lines.push('    pin: GPIO2')
    lines.push('')
    lines.push('light:')
    lines.push('  - platform: neopixelbus')
    lines.push('    id: status_light')
    lines.push('    name: "Status Light"')
    lines.push('    pin: GPIO27')
    lines.push('    num_leds: 1')
    lines.push('    type: GRB')
    lines.push('')

    // Automations (on_... sections)
    lines.push('# ── Automations ───────────────────────────────────────')

    for(const block of program.blocks) {
      if(block.kind!=='when') continue
      const automation = triggerToESPHome(block.trigger, block.body)
      if(automation) lines.push(...automation, '')
    }

    return { code: lines.join('\n') }
  }
}

function triggerToESPHome(trigger: Trigger, body: Statement[]): string[]|null {
  const actions = bodyToESPHome(body)
  switch(trigger.kind) {
    case 'button_a':
      return ['button:', '  - platform: gpio', '    pin: GPIO0', '    name: "Button A"', '    on_press:', ...actions.map(a=>'      '+a)]
    case 'sensor':
      return [`# Sensor automation: ${trigger.sensor} ${trigger.op} ${trigger.threshold}`,
              `# Add to your sensor's on_value_range section`]
    case 'motion':
      return ['# Motion automation:', `# Add to binary_sensor.motion_sensor on_press:`, ...actions.map(a=>'#   '+a)]
    case 'timer':
      return [`interval:`, `  - interval: ${trigger.interval.value}${trigger.interval.unit}`, `    then:`, ...actions.map(a=>'      '+a)]
    case 'time_of_day': {
      const h=String(trigger.hour).padStart(2,'0'), m=String(trigger.minute).padStart(2,'0')
      return [`time:`, `  - platform: homeassistant`, `    id: ha_time`, `    on_time:`, `      - hours: ${h}`, `        minutes: ${m}`, `        then:`, ...actions.map(a=>'          '+a)]
    }
    default: return null
  }
}

function bodyToESPHome(stmts: Statement[]): string[] {
  const lines: string[] = []
  for(const stmt of stmts) {
    switch(stmt.kind) {
      case 'lights_on':  lines.push(`- light.turn_on: status_light`); break
      case 'lights_off': lines.push(`- light.turn_off: status_light`); break
      case 'lights_dim': lines.push(`- light.dim_relative: {entity_id: status_light}`); break
      case 'thermostat': lines.push(`# set thermostat — connect to HA via API`); break
      case 'notify':     lines.push(`- logger.log: "Notification sent"`); break
      case 'say':        lines.push(`- logger.log: "Message"`); break
      case 'play':       lines.push(`- output.ledc.set_frequency: {id: buzzer_output, frequency: 440hz}`,`- output.set_level: {id: buzzer_output, level: 50%}`,`- delay: 200ms`,`- output.turn_off: buzzer_output`); break
      case 'wait':       lines.push(`- delay: ${stmt.duration.value}${stmt.duration.unit}`); break
      case 'lock':       lines.push(`# lock ${stmt.device??'door'} — connect to HA lock entity`); break
      case 'unlock':     lines.push(`# unlock ${stmt.device??'door'} — connect to HA lock entity`); break
      case 'scene':      lines.push(`# set scene: ${stmt.name}`); break
      case 'show':       lines.push(`- light.turn_on: {id: status_light, effect: "${stmt.expression}"}`); break
      case 'stop':       lines.push(`- logger.log: "Stop"`); break
      case 'if':
        lines.push(`- if:`,`    condition:`,`      lambda: 'return true; /* ${stmt.condition.kind} */'`,`    then:`)
        lines.push(...bodyToESPHome(stmt.then).map(l=>'      '+l))
        break
      default: lines.push(`# [${stmt.kind}]`); break
    }
  }
  return lines
}

function usesFeature(program: Program, feature: string): boolean {
  return JSON.stringify(program).includes(`"sensor":"${feature}"`)
}
function usesTrigger(program: Program, kind: string): boolean {
  return program.blocks.some(b=>b.kind==='when'&&b.trigger.kind===kind)
}
