// AppyScript → MicroPython (BBC micro:bit V2)
// Uses the microbit module. 5x5 LED display, 2 buttons, accelerometer.

import type {
  Program, Block, Statement, Trigger, Condition, Value, Duration, FaceExpression,
} from '../ast'

function durationMs(d: Duration): number {
  if (d.unit === 'ms') return d.value
  if (d.unit === 's') return d.value * 1000
  return d.value * 60000
}

// Map AppyScript expressions to micro:bit built-in Image names
const MICROBIT_IMAGES: Record<FaceExpression, string> = {
  happy: 'Image.HAPPY',
  sad: 'Image.SAD',
  thinking: 'Image.SURPRISED',
  excited: 'Image.YES',
  angry: 'Image.ANGRY',
  alert: 'Image.SURPRISED',
  sleep: 'Image.ASLEEP',
  calm: 'Image.CALM',
  confused: 'Image.CONFUSED',
  dizzy: 'Image.ROLL',
}

export function generateMicrobit(program: Program): string {
  const gen = new MicrobitGenerator()
  return gen.generate(program)
}

class MicrobitGenerator {
  private lines: string[] = []
  private indent = 0
  private definedFunctions = new Set<string>()

  generate(program: Program): string {
    this.emit('# Generated by AppyScript — https://github.com/rahulbachina/appyscript')
    this.emit('# Target: BBC micro:bit V2 (MicroPython)')
    this.emit('')
    this.emit('from microbit import *')
    this.emit('import utime')
    this.emit('')

    const defines = program.blocks.filter(b => b.kind === 'define')
    const others = program.blocks.filter(b => b.kind !== 'define')

    for (const block of defines) {
      if (block.kind !== 'define') continue
      this.definedFunctions.add(block.name)
      this.emit(`def ${block.name}():`)
      this.indent++
      this.emitStatements(block.body)
      this.indent--
      this.emit('')
    }

    // micro:bit uses a simple polling loop — no async
    const whenBlocks = others.filter(b => b.kind === 'when')
    const foreverBlocks = others.filter(b => b.kind === 'forever')
    const startBlocks = whenBlocks.filter(b => b.kind === 'when' && b.trigger.kind === 'start')
    const pollBlocks = whenBlocks.filter(b => b.kind === 'when' && b.trigger.kind !== 'start')

    // Run start blocks once
    for (const b of startBlocks) {
      if (b.kind === 'when') this.emitStatements(b.body)
    }

    if (pollBlocks.length > 0 || foreverBlocks.length > 0) {
      this.emit('while True:')
      this.indent++

      for (const block of pollBlocks) {
        if (block.kind !== 'when') continue
        const condition = this.triggerToCondition(block.trigger)
        if (condition) {
          this.emit(`if ${condition}:`)
          this.indent++
          this.emitStatements(block.body)
          this.indent--
        }
      }

      for (const block of foreverBlocks) {
        if (block.kind !== 'forever') continue
        this.emitStatements(block.body)
      }

      this.emit('sleep(50)')
      this.indent--
    }

    return this.lines.join('\n')
  }

  private triggerToCondition(trigger: Trigger): string | null {
    switch (trigger.kind) {
      case 'button_a': return 'button_a.is_pressed()'
      case 'button_b': return 'button_b.is_pressed()'
      case 'shaken': return 'accelerometer.is_gesture("shake")'
      case 'tilted':
        if (trigger.direction === 'left') return 'accelerometer.is_gesture("left")'
        if (trigger.direction === 'right') return 'accelerometer.is_gesture("right")'
        return 'accelerometer.is_gesture("face up")'
      case 'sensor': {
        const call = this.sensorCall(trigger.sensor)
        return `${call} ${trigger.op} ${trigger.threshold}`
      }
      default: return null
    }
  }

  private sensorCall(sensor: string): string {
    const map: Record<string, string> = {
      distance: '999',  // micro:bit has no built-in distance sensor — returns 999 (not available)
      light: 'display.read_light_level()',
      temperature: 'temperature()',
      touch: 'pin_logo.is_touched()',
      acceleration: 'abs(accelerometer.get_z())',
    }
    return map[sensor] ?? '0'
  }

  private emitStatements(stmts: Statement[]) {
    if (stmts.length === 0) { this.emit('pass'); return }
    for (const stmt of stmts) this.emitStatement(stmt)
  }

  private emitStatement(stmt: Statement) {
    switch (stmt.kind) {
      case 'move':
        // micro:bit has no motors built in — write to pin0/pin1 for motor driver
        this.emit(`# motor: ${stmt.direction} speed=${stmt.speed ?? 50}`)
        this.emit(`pin0.write_analog(${Math.round((stmt.speed ?? 50) * 10.23)})`)
        if (stmt.duration) {
          this.emit(`sleep(${durationMs(stmt.duration)})`)
          this.emit('pin0.write_analog(0)')
          this.emit('pin1.write_analog(0)')
        }
        break
      case 'turn':
        this.emit(`# turn ${stmt.direction} ${stmt.degrees}°`)
        break
      case 'stop':
        this.emit('pin0.write_analog(0)')
        this.emit('pin1.write_analog(0)')
        break
      case 'say':
        this.emit(`display.scroll(${JSON.stringify(stmt.text)})`)
        break
      case 'play':
        this.emit(`# play "${stmt.sound}"`)
        this.emit('audio.play(audio.SoundEffect(freq_start=440, freq_end=440, duration=500))')
        break
      case 'show':
        this.emit(`display.show(${MICROBIT_IMAGES[stmt.expression] ?? 'Image.HAPPY'})`)
        break
      case 'show_text':
        this.emit(`display.scroll(${JSON.stringify(stmt.text)})`)
        break
      case 'show_number':
        this.emit(`display.scroll(str(${this.emitValue(stmt.value)}))`)
        break
      case 'wait':
        this.emit(`sleep(${durationMs(stmt.duration)})`)
        break
      case 'let':
        this.emit(`${stmt.name} = ${this.emitValue(stmt.value)}`)
        break
      case 'set':
        this.emit(`${stmt.name} = ${this.emitValue(stmt.value)}`)
        break
      case 'do':
        this.emit(`${stmt.name}()`)
        break
      case 'if':
        this.emit(`if ${this.emitCondition(stmt.condition)}:`)
        this.indent++
        this.emitStatements(stmt.then)
        this.indent--
        if (stmt.else) {
          this.emit('else:')
          this.indent++
          this.emitStatements(stmt.else)
          this.indent--
        }
        break
      case 'repeat': {
        this.emit(`for _i in range(${this.emitValue(stmt.count)}):`)
        this.indent++
        this.emitStatements(stmt.body)
        this.indent--
        break
      }
      case 'while':
        this.emit(`while ${this.emitCondition(stmt.condition)}:`)
        this.indent++
        this.emitStatements(stmt.body)
        this.emit('sleep(10)')
        this.indent--
        break
    }
  }

  private emitValue(value: Value): string {
    switch (value.kind) {
      case 'number': return String(value.value)
      case 'string': return JSON.stringify(value.value)
      case 'bool': return value.value ? 'True' : 'False'
      case 'variable': return value.name
      case 'sensor': return this.sensorCall(value.sensor)
      case 'binary':
        return `(${this.emitValue(value.left)} ${value.op} ${this.emitValue(value.right)})`
    }
  }

  private emitCondition(cond: Condition): string {
    switch (cond.kind) {
      case 'sensor': return `${this.sensorCall(cond.sensor)} ${cond.op} ${cond.threshold}`
      case 'variable': return `${cond.name} ${cond.op} ${this.emitValue(cond.value)}`
      case 'bool': return cond.value ? 'True' : 'False'
      case 'not': return `not (${this.emitCondition(cond.condition)})`
      case 'and': return `(${this.emitCondition(cond.left)}) and (${this.emitCondition(cond.right)})`
      case 'or': return `(${this.emitCondition(cond.left)}) or (${this.emitCondition(cond.right)})`
    }
  }

  private emit(line: string) {
    this.lines.push('    '.repeat(this.indent) + line)
  }
}
